server.port=8215

# spring.datasource.url=jdbc:postgresql://localhost:5432/TimeSy
# spring.datasource.username=TimeSy
# spring.datasource.password=TimeSy
# spring.datasource.driver-class-name=org.postgresql.Driver # Spring Boot can infer this from the URL
# spring.jpa.show-sql=true

templates.folder=""
heonline.url=127.0.0.1:8081
displayserver.url=""

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true
# spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect